### ISSUE TITLE
[FEATURE REQUEST] Add headless browser

### ISSUE THREAD

**Issue by DarkSkull91** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#225]
Why don't add an headless browser like PhantomJS (for python take a look to this page **https://stackoverflow.com/questions/6025082/headless-browser-for-python-javascript-support-required**)  to run this wonderful application also in a command line environment? Think to people that have a raspberry pi server that runs only without a GUI.

**Comment by fakeid30** [comment]
@DarkSkull91 this possesses additional challenges that we need to cover (like if/when they hit a captcha, if/when udemy changes their css, if/when they require a new zipcode from a country) which I don't think is boilerplate or easy. This will increase maintenance hurdle and one thing we decided to do early is to not cover every niche case possible. 

This software is not meant to run from a headless instance because 2-3 mins a day is enough to get everything and you most people that would need free udemy courses, have a computer. 

Marking this as wontfix because of those reasons. But that being said, we will review and accept a good PR with all the test coverage and primary cases covered. 

Please comment if you have further questions.
