### ISSUE TITLE
[FEATURE REQUEST] Allow empty password in yaml

### ISSUE THREAD

**Issue by Destroy666x** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#260]
Problem: password is either saved in plain text yaml, which is not secure, or everything including password needs to be entered each time, which is tedious.

Solution: allow to skip entering password during settings set up. Then check if it's empty before running requests to Udemy (login function) and prompt for it when it is.

**Comment by sh-sabbir** [comment]
I might have a simple but better solution. This can be fixed easily with base64+a bit of brain game. 

For example: our password is `1123435` and the base64 value is `MTEyMzQzNQ==`

Now if we remove `==` we have `MTEyMzQzNQ` and we can easily calculate the length of this. In this case it' `10`.

Let's make our own encryption! 

Split `MTEyMzQzNQ` in to two part 

```
A = MTEyM
B = zQzNQ
Length = 10 
```
new base64 string will be either `L+B+A` or `B+A+L`. Let's add `==` at the end. So possible encrypted password string could be either `zQzNQMTEyM10==` or `10zQzNQMTEyM==`

Note: Not always the encrypted string will be even digit. In that case we have to decide which portion will be larger. It's not the best solution but it's a simple and effective solution so store the password without having it as a plain text.

**Comment by fakeid30** [comment]
@sh-sabbir this is a very good solution :D thank you. Should be easy enough to implement. 

@cullzie what do you say?

**Comment by cullzie** [comment]
@sh-sabbir This is a possible solution but since this code is open source it would be trivial to reverse engineer. It is definitely a big improvement over the current implementation :+1: 

@fakeid30 We can add some encryption on the username/password fields in the settings file but then the user will need to either input their encryption password each time the cookie expires or have a private key generated and stored locally which can be used for decryption. If someone gains access to your local PC though they will have access to private keys and potential to gain access to passwords

@Destroy666x We can create the settings with empty password and username. The prompt on startup can be changed to `save username y/n?` and `save password y/n?` Then you should only be prompted when the cookie expires

**Comment by cullzie** [comment]
I have a PR for this soon. Basically we will ask the user if they want to save email/password individually. So we can store the email in settings but not password for example or whatever combo of those 2 suits. The user will get prompted for the missing info if there is no cookie existing or if it has expired.

We will store other settings by default (zip, categories, languages). If the user wants to update they can edit or delete the existing settings.yaml
