### ISSUE TITLE
Create a toggle in settings.yaml that lets the script stop after pre-selected pages

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#33]
[Implementing this closed PR in a modular way is ideal](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/pull/11)

**Comment by ethankrein** [comment]
I can take this when I go over some of the other setting additions.

**Comment by fakeid30** [comment]
@cullzie what's your thought on this ?

**Comment by cullzie** [comment]
@fakeid30 instead of putting it into settings I think it would be better adding it as a cli argument. What do you think? So you'd call `udemy_enroller_chrome.py --max_pages=5`
It would also be possible to move to a one file entry point with this `udemy_enroller.py --browser=chrome` which would probably be necessary for release on pypi

**Comment by fakeid30** [comment]
@cullzie yeah --max-pages = X approach is workable 👍🏽
