### ISSUE TITLE
[FEATURE REQUEST] Dockerize it

### ISSUE THREAD

**Issue by bugbounted** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#376]
Hi [Antariksh Patre](https://github.com/aapatre),
please dockerize this project for easy deplot to cloud containers
waiting for your commits
finest regards

**Comment by cullzie** [comment]
Hey @elmirarokni , What is the benefit of dockerizing this script? It is very basic setup and I can't see what benefit could be gained from this

**Comment by elmirarokni** [comment]
hello  [cullzie](https://github.com/cullzie),
dockerize is so recommended for deploy main branch in cloud contaniers like kubernate or heroku or ... 
udemy-enroller package must be change to dockerfile on build  selenium structure or using standard buildpacks like :
https://elements.heroku.com/buildpacks/pyronlaboratory/heroku-integrated-firefox-geckodriver
if make dockerfile in root much better than make it compatable to heroku buildpacks because it can be run on any cloud contaniers.
you can see simple Dockerfile and python script to run selenium with headless chromedriver in debian docker container below :
https://gist.github.com/matt-bertoncello/a7296c4fc6cdbb8424ffa26b2b9b9257
but must be change parts of udemy-enroller package  & selenium drivers to work in docker without issue.
waiting for your commit/s or build unique branch for docker friendly version.
finest regards

**Comment by cullzie** [comment]
@bugbounted The package has been added to a docker container in the PR linked. 
It will work with the REST based enrollment. We will make a release soon to pypi in the meantime you can check it out on the develop branch. Thanks
